ENTER  7 ELEMENTS                                                               
1                                                                               
2                                                                               
3                                                                               
4                                                                               
5                                                                               
6                                                                               
7                                                                               
ARRAY BEFORE INSERTION                                                          
1234567                                                                         
ENTER THE ELEMENT TO BE INSERTED                                                
8                                                                               
ENTER THE POSITION AT WHICH THE ELEMENT IS TO BE INSERTED                       
1                                                                               
ARRAY AFTER INSERTION                                                           
81234567                                                                        
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
ENTER  7 ELEMENTS                                                               
1                                                                               
2                                                                               
3                                                                               
4                                                                               
5                                                                               
6                                                                               
7                                                                               
ARRAY BEFORE INSERTION                                                          
1234567                                                                         
ENTER THE ELEMENT TO BE INSERTED                                                
8                                                                               
ENTER THE POSITION AT WHICH THE ELEMENT IS TO BE INSERTED                       
1                                                                               
ARRAY AFTER INSERTION                                                           
81234567                                                                        
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
